### ISSUE TITLE
v2 Documentation

### ISSUE THREAD

**Issue by stephenl03** [cloudpassage/cloudpassage-halo-python-sdk#192]
This might not be the correct location for this, but the Cloudpassage API documents do not expand on the v2 endpoint capabilities. However, the SDK is now including this endpoint, so I thought it would be fitting to create an issue about it now. When will the API Documents be updated to include the additional features?

**Comment by ashmastaflash** [comment]
Hi @stephenl03 thanks for reaching out!
The endpoints that are documented in the API guide (https://api-doc.cloudpassage.com/help) are officially supported. We added a version selector for endpoint abstractions to make future revisions easier, and to make it easier for users to pin to a specific version of the API, when we increment the default version that the abstraction points to. This also allows you to use the named abstraction instead of taking it all the way down to HttpHelper to use non-default endpoint versions.

I think that the request for improved documentation is perfectly reasonable- I think we could improve this by adding the URLs for different API versions to the SDK docs, so you don't have to search as much to find what you're looking for.

Which endpoints/versions are most interesting to you?

**Comment by stephenl03** [comment]
I know specifically the `/v1/special_events_policies/{id}` endpoint returns metadata information regarding the special events policy whereas `/v2/special_events_policies/{id}` returns the actual policy. Additionally, the `v1` endpoint for policies does not allow you to create a special events policy, whereas the `v2` endpoint does.

**Comment by ashmastaflash** [comment]
Those endpoints are used primarily by the UI, and are subject to change. The SDK can still be used for interacting with those endpoints, though.

All that being said, I'll pass your feedback along to the product team.
